services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6.3-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - caddy
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  caddy:
    image: caddy:2.8.4-alpine
    depends_on:
      - php-fpm
    environment:
      VIRTUAL_HOST: ${DOMAIN}
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
  php-fpm:
    image: php:8.3.9-fpm-alpine
    volumes:
      - .:/app

networks:
  proxy:
    name: proxy
    external: true

volumes:
  caddy-data:
  caddy-config: